In [1]:
import pandas as pd

# 1 Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [8]:
# reading 1 csv file from the website
df_premier24 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [9]:
# showing dataframe
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [10]:
# rename columns
df_premier24.rename(columns={'FTHG': 'home_goals',
                             'FTAG': 'away_goals'},
                   inplace=True)

In [11]:
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

# 2 Read .csv from Multiple URLs with Pandas

https://www.football-data.co.uk/mmz4281/2425/E0.csv

https://www.football-data.co.uk/mmz4281/2425/E1.csv

https://www.football-data.co.uk/mmz4281/2425/E2.csv

Link: root + season + league

In [19]:
# link structure
'https://www.football-data.co.uk/mmz4281' + '2425' + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz42812425/E0.csv'

In [21]:
# create a root variable
root = 'https://www.football-data.co.uk/mmz4281'
season = '2425'

# creating list of leagues
leagues = ["E0", "E1", "E2", "E3", "EC"]

In [22]:
frames = []

# looging through leagues, read multiple csv and appedn it into a list
for league in leagues:
    df = pd.read_csv(f'{root}/{season}/{league}.csv')
    frames.append(df)

In [23]:
# length of frames
len(frames)

5

In [25]:
# show 1st, 2nd and 3rd element
frames[:3]

[    Div        Date   Time       HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    E0  16/08/2024  20:00     Man United       Fulham     1     0   H     0
 1    E0  17/08/2024  12:30        Ipswich    Liverpool     0     2   A     0
 2    E0  17/08/2024  15:00        Arsenal       Wolves     2     0   H     1
 3    E0  17/08/2024  15:00        Everton     Brighton     0     3   A     0
 4    E0  17/08/2024  15:00      Newcastle  Southampton     1     0   H     1
 ..   ..         ...    ...            ...          ...   ...   ...  ..   ...
 375  E0  25/05/2025  16:00      Newcastle      Everton     0     1   A     0
 376  E0  25/05/2025  16:00  Nott'm Forest      Chelsea     0     1   A     0
 377  E0  25/05/2025  16:00    Southampton      Arsenal     1     2   A     0
 378  E0  25/05/2025  16:00      Tottenham     Brighton     1     4   A     1
 379  E0  25/05/2025  16:00         Wolves    Brentford     1     1   D     0

      HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0       0  ...     1.86     2.07   1.83   2.11     1.88     2.11     1.82
 1       0  ...     2.05     1.88   2.04   1.90     2.20     2.00     1.99
 2       0  ...     2.02     1.91   2.00   1.90     2.05     1.93     1.99
 3       1  ...     1.87     2.06   1.86   2.07     1.92     2.10     1.83
 4       0  ...     1.87     2.06   1.88   2.06     1.89     2.10     1.82
 ..    ...  ...      ...      ...    ...    ...      ...      ...      ...
 375     0  ...     2.00     1.85   2.01   1.90     2.01     1.95     1.95
 376     0  ...     1.80     2.05   1.86   2.08     1.86     2.08     1.81
 377     1  ...     2.03     1.83   2.04   1.87     2.07     1.87     2.03
 378     0  ...     1.95     1.90   2.00   1.93     2.01     1.93     1.95
 379     1  ...     1.85     2.00   1.90   2.03     1.90     2.05     1.85

      AvgCAHA  BFECAHH  BFECAHA
 0       2.05     1.90     2.08
 1       1.88     2.04     1.93
 2       1.87     2.02     1.96
 3       2.04     1.88     2.11
 4       2.05     1.89     2.10
 ..       ...      ...      ...
 375     1.91     1.93     2.05
 376     2.05     1.86     2.14
 377     1.83     2.06     1.89
 378     1.89     2.06     1.93
 379     1.97     1.89     2.10

 [380 rows x 120 columns],
     Div        Date   Time          HomeTeam          AwayTeam  FTHG  FTAG  \
 0    E1  09/08/2024  20:00         Blackburn             Derby     4     2
 1    E1  09/08/2024  20:00           Preston  Sheffield United     0     2
 2    E1  10/08/2024  12:30           Cardiff        Sunderland     0     2
 3    E1  10/08/2024  12:30              Hull      Bristol City     1     1
 4    E1  10/08/2024  12:30             Leeds        Portsmouth     3     3
 ..   ..         ...    ...               ...               ...   ...   ...
 547  E1  03/05/2025  12:30  Sheffield United         Blackburn     1     1
 548  E1  03/05/2025  12:30        Sunderland               QPR     0     1
 549  E1  03/05/2025  12:30           Swansea            Oxford     3     3
 550  E1  03/05/2025  12:30           Watford    Sheffield Weds     1     1
 551  E1  03/05/2025  12:30         West Brom             Luton     5     3

     FTR  HTHG  HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  \
 0     H     1     0  ...     1.85     2.05   1.85   2.06     1.97     2.10
 1     A     0     1  ...     1.92     1.98   1.93   1.98     1.97     1.99
 2     A     0     1  ...     2.11     1.79   2.13   1.80     2.13     1.81
 3     D     0     0  ...     1.99     1.91   2.00   1.91     2.04     1.91
 4     D     1     2  ...     1.92     1.98   1.93   1.95     2.00     1.98
 ..   ..   ...   ...  ...      ...      ...    ...    ...      ...      ...
 547   D     0     0  ...     1.89     2.01   1.90   2.01     1.91     2.11
 548   A     0     1  ...     2.01     1.89   2.04   1.88     2.19     1.89
 549   D     1     1  ...     2.02     1.88   2.03   1.88     2.08     1.89
 550   D     1     1  ...     1.85     2.00   1.86   2.05     2.00     2.05
 551   H     3     1  ...     1.91     1.99   1.89   2.01     1.97     2.01

      AvgCAHH  AvgCAHA  BFECAHH  BFECAHA
 0       1.85     1.99     1.88     2.11
 1       1.90     1.94     1.94     2.04
 2       2.09     1.79     2.18     1.83
 3       1.99     1.87     2.03     1.96
 4       1.94     1.89     2.00     1.97
 ..       ...      ...      ...      ...
 547     1.84     2.04     1.89     2.10
 548     2.04     1.81     2.16     1.82
 549     2.00     1.85     2.09     1.89
 550     1.92     1.94     2.00     1.99
 551     1.87     1.94     1.92     2.05

 [552 rows x 120 columns],
     Div        Date   Time      HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    E2  09/08/2024  20:00      Barnsley     Mansfield     1     2   A     1
 1    E2  10/08/2024  17:30    Birmingham       Reading     1     1   D     0
 2    E2  10/08/2024  17:30   Bristol Rvs   Northampton     1     0   H     0
 3    E2  10/08/2024  17:30        Burton       Lincoln     2     3   A     2
 4    E2  10/08/2024  17:30  Crawley Town     Blackpool     2     1   H     2
 ..   ..         ...    ...           ...           ...   ...   ...  ..   ...
 547  E2  03/05/2025  15:00   Northampton         Wigan     1     1   D     1
 548  E2  03/05/2025  15:00       Reading      Barnsley     2     4   A     0
 549  E2  03/05/2025  15:00     Rotherham     Peterboro     2     1   H     1
 550  E2  03/05/2025  15:00    Shrewsbury  Crawley Town     1     2   A     0
 551  E2  03/05/2025  15:00       Wycombe     Stockport     1     3   A     1

      HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0       2  ...     2.03     1.83   2.02   1.87     2.05     2.00     1.95
 1       1  ...     1.80     2.05   1.81   2.10     1.83     2.10     1.80
 2       0  ...     1.98     1.88   1.98   1.91     1.98     1.92     1.93
 3       2  ...     1.80     2.05   1.82   2.08     1.88     2.09     1.80
 4       0  ...     1.83     2.03   1.85   2.04     1.86     2.05     1.82
 ..    ...  ...      ...      ...    ...    ...      ...      ...      ...
 547     0  ...     2.05     1.80   2.09   1.78     2.11     1.80     2.03
 548     0  ...     1.85     2.00   1.79   2.07     1.85     2.12     1.79
 549     1  ...     1.93     1.93   1.93   1.92     2.00     1.95     1.91
 550     0  ...     2.03     1.83   2.05   1.81     2.10     1.83     2.03
 551     0  ...     1.85     2.00   1.87   1.99     1.87     2.15     1.80

      AvgCAHA  BFECAHH  BFECAHA
 0       1.85     2.06     1.93
 1       2.01     1.82     2.16
 2       1.86     2.02     1.97
 3       2.01     1.88     2.11
 4       1.99     1.89     2.08
 ..       ...      ...      ...
 547     1.78     2.13     1.84
 548     2.03     1.87     2.11
 549     1.89     1.98     2.00
 550     1.79     2.11     1.87
 551     2.04     1.88     2.11

 [552 rows x 120 columns]]

# 2.2 Multiple Seasons

In [29]:
for season in range(19,25):
    print(str(season) + str(season + 1))

1920
2021
2122
2223
2324
2425

In [42]:
# create a root variable
root = 'https://www.football-data.co.uk/mmz4281'
# seasons = '2425'

# creating list of leagues
leagues = ["E0", "E1", "E2"]

frames = []

# looging through leagues, read multiple csv and appedn it into a list
for league in leagues:
    for season in range(19,25):
        df = pd.read_csv(f'{root}/{str(season) + str(season + 1)}/{league}.csv')
        df.insert(1, 'season', season)
        frames.append(df)

In [43]:
# total frames (6 season x 3 league)
len(frames)

18

In [46]:
# show 1st, 2nd and 3rd element (new sesason column was created)
frames[-1]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,24,09/08/2024,20:00,Barnsley,Mansfield,1,2,A,1,...,2.03,1.83,2.02,1.87,2.05,2.00,1.95,1.85,2.06,1.93
1,E2,24,10/08/2024,17:30,Birmingham,Reading,1,1,D,0,...,1.80,2.05,1.81,2.10,1.83,2.10,1.80,2.01,1.82,2.16
2,E2,24,10/08/2024,17:30,Bristol Rvs,Northampton,1,0,H,0,...,1.98,1.88,1.98,1.91,1.98,1.92,1.93,1.86,2.02,1.97
3,E2,24,10/08/2024,17:30,Burton,Lincoln,2,3,A,2,...,1.80,2.05,1.82,2.08,1.88,2.09,1.80,2.01,1.88,2.11
4,E2,24,10/08/2024,17:30,Crawley Town,Blackpool,2,1,H,2,...,1.83,2.03,1.85,2.04,1.86,2.05,1.82,1.99,1.89,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,24,03/05/2025,15:00,Northampton,Wigan,1,1,D,1,...,2.05,1.80,2.09,1.78,2.11,1.80,2.03,1.78,2.13,1.84
548,E2,24,03/05/2025,15:00,Reading,Barnsley,2,4,A,0,...,1.85,2.00,1.79,2.07,1.85,2.12,1.79,2.03,1.87,2.11
549,E2,24,03/05/2025,15:00,Rotherham,Peterboro,2,1,H,1,...,1.93,1.93,1.93,1.92,2.00,1.95,1.91,1.89,1.98,2.00
550,E2,24,03/05/2025,15:00,Shrewsbury,Crawley Town,1,2,A,0,...,2.03,1.83,2.05,1.81,2.10,1.83,2.03,1.79,2.11,1.87
551,E2,24,03/05/2025,15:00,Wycombe,Stockport,1,3,A,1,...,1.85,2.00,1.87,1.99,1.87,2.15,1.80,2.04,1.88,2.11

# 3 Organize All The Data in a Dictionary