In [2]:
import pandas as pd

In [6]:
# reading the csvfile
df_population_raw = pd.read_csv('population_total.csv')

In [7]:
# first look at the dataset
df_population_raw

            country    year    population
0             China  2020.0  1.439324e+09
1             China  2019.0  1.433784e+09
2             China  2018.0  1.427648e+09
3             China  2017.0  1.421022e+09
4             China  2016.0  1.414049e+09
...             ...     ...           ...
4180  United States  1965.0  1.997337e+08
4181  United States  1960.0  1.867206e+08
4182  United States  1955.0  1.716853e+08
4183          India  1960.0  4.505477e+08
4184          India  1955.0  4.098806e+08

[4185 rows x 3 columns]

# Making a Pivot Table

.pivot(): Returns reshaped DataFrame organized by given index / column values ("pivot without aggregation")

In [10]:
# dropping null values
df_population_raw.dropna(inplace=True)

In [29]:
# making a pivot table
df_population_table = df_population_raw.pivot_table(index='year', columns="country", values="population")
df_population_table

country,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Wallis & Futuna,Western Sahara,Yemen,Zambia,Zimbabwe
year,,,,,,,,,,,,,,,,,,,,,
1955.0,8270991.0,1419994.0,9774283.0,19754.0,9232.0,5043247.0,5783.0,49648.0,18789418.0,1563507.0,...,2372559.0,7277333.0,54921.0,6744695.0,28147443.0,7669.0,21147.0,4965574.0,2644976.0,3213286.0
1960.0,8996973.0,1636090.0,11057863.0,20123.0,13411.0,5454933.0,6032.0,54131.0,20481779.0,1874121.0,...,2538643.0,8526300.0,63689.0,8141841.0,32670039.0,8157.0,32761.0,5315355.0,3070776.0,3776681.0
1965.0,9956320.0,1896171.0,12550885.0,23672.0,18549.0,5770570.0,6361.0,58698.0,22159650.0,2211319.0,...,2694536.0,10116870.0,74270.0,9692278.0,37858951.0,8724.0,50970.0,5727751.0,3570464.0,4471177.0
1970.0,11173642.0,2150707.0,14464985.0,27363.0,24276.0,5890365.0,6771.0,64177.0,23880561.0,2525068.0,...,2809793.0,12080317.0,85377.0,11396393.0,43404793.0,8853.0,76874.0,6193384.0,4179067.0,5289303.0
1975.0,12689160.0,2411732.0,16607707.0,30052.0,30705.0,7024000.0,7159.0,62675.0,25865776.0,2832759.0,...,2830176.0,13857478.0,99859.0,13189509.0,48718189.0,9320.0,74954.0,6784695.0,4943283.0,6293875.0
1980.0,13356511.0,2682690.0,19221665.0,32646.0,36067.0,8341289.0,7285.0,61865.0,27896528.0,3099754.0,...,2915389.0,15898757.0,115597.0,15182611.0,54281846.0,11231.0,150877.0,7941898.0,5851825.0,7408624.0
1985.0,11938208.0,2969672.0,22431502.0,39519.0,44600.0,9961997.0,7293.0,61786.0,30216279.0,3335940.0,...,3011519.0,18061284.0,129984.0,17319520.0,60896721.0,13622.0,182421.0,9572175.0,6923149.0,8877489.0
1990.0,12412308.0,3286073.0,25758869.0,47347.0,54509.0,11848386.0,8899.0,62528.0,32618651.0,3538171.0,...,3109601.0,20398348.0,146573.0,19632665.0,67988862.0,13800.0,217258.0,11709993.0,8036845.0,10432421.0
1995.0,18110657.0,3112936.0,28757785.0,53161.0,63850.0,13945206.0,9866.0,68670.0,34828170.0,3217348.0,...,3224281.0,22791026.0,168158.0,21931084.0,74910461.0,14149.0,255634.0,14913315.0,9096607.0,11410714.0
2000.0,20779953.0,3129243.0,31042235.0,57821.0,65390.0,16395473.0,11252.0,76016.0,36870787.0,3069591.0,...,3319736.0,24769955.0,184972.0,24192446.0,79910412.0,14694.0,314118.0,17409072.0,10415944.0,11881477.0
2005.0,25654277.0,3086810.0,33149724.0,59562.0,78867.0,19433602.0,12453.0,81465.0,38892931.0,2981269.0,...,3321803.0,26427789.0,209282.0,26432447.0,83832661.0,14939.0,437515.0,20107409.0,11856247.0,12076699.0
2010.0,29185507.0,2948023.0,35977455.0,56079.0,84449.0,23356246.0,13438.0,88028.0,40895752.0,2877319.0,...,3359275.0,28515909.0,236211.0,28439940.0,87967651.0,12689.0,480274.0,23154855.0,13605984.0,12697723.0
2015.0,34413603.0,2890513.0,39728025.0,55812.0,78011.0,27884381.0,14279.0,93566.0,43075416.0,2925553.0,...,3412009.0,30929557.0,271130.0,30081829.0,92677076.0,12266.0,526216.0,26497889.0,15879361.0,13814629.0
2016.0,35383032.0,2886438.0,40551392.0,55741.0,77297.0,28842489.0,14429.0,94527.0,43508460.0,2936143.0,...,3424129.0,31441751.0,278330.0,29851255.0,93640422.0,12107.0,538749.0,27168208.0,16363458.0,14030331.0
2017.0,36296113.0,2884169.0,41389189.0,55620.0,77001.0,29816766.0,14584.0,95426.0,43937140.0,2944791.0,...,3436641.0,31959785.0,285510.0,29402484.0,94600648.0,11900.0,552615.0,27834819.0,16853599.0,14236595.0
2018.0,37171921.0,2882740.0,42228408.0,55465.0,77006.0,30809787.0,14731.0,96286.0,44361150.0,2951745.0,...,3449285.0,32476244.0,292680.0,28887118.0,95545962.0,11661.0,567402.0,28498683.0,17351708.0,14438802.0
2019.0,38041754.0,2880917.0,43053054.0,55312.0,77142.0,31825295.0,14869.0,97118.0,44780677.0,2957731.0,...,3461734.0,32981716.0,299882.0,28515829.0,96462106.0,11432.0,582463.0,29161922.0,17861030.0,14645468.0
2020.0,38928346.0,2877797.0,43851044.0,NaN,NaN,32866272.0,NaN,97929.0,45195774.0,2963243.0,...,3473730.0,33469203.0,307145.0,28435940.0,97338579.0,NaN,597339.0,29825964.0,18383955.0,14862924.0

In [32]:
# selecting some countries
df_pivot = df_population_table[["Russia", "India", "China", "Indonesia", "Brazil"]]

In [33]:
# showing pivot table
df_pivot

country       Russia         India         China    Indonesia       Brazil
year
1955.0   111355300.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960.0   119871700.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965.0   126503736.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970.0   130148653.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975.0   133804858.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980.0   138053150.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985.0   142957284.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990.0   147531561.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995.0   148227466.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000.0   146404903.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005.0   143672116.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010.0   143479274.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015.0   144985057.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016.0   145275383.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017.0   145530082.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018.0   145734038.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019.0   145872256.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020.0   145934462.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0