In [8]:
import pandas as pd

# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1 Create index

In [2]:
import numpy as np
import random

In [4]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)

In [6]:
# shuffling the indexes
random.shuffle(new_index)
new_index

array([108, 305, 152, 180, 393, 323, 381,  10, 800, 431, 580, 253,  60,
       857, 140, 889, 481, 508, 661, 873, 791, 506, 144, 859, 751, 450,
       802, 974, 364, 877, 486, 187, 685, 382, 271, 371, 912, 359, 855,
       796,  11, 898, 760, 550, 213,   3, 606, 854, 665, 841, 185, 130,
       198, 703, 230, 923, 404, 215, 824, 710, 490, 210, 502, 254, 624,
       688, 785,  78, 989,  24,  71, 874, 865,  12, 831,  57, 743, 598,
        35,   2, 956,  40, 689, 484, 619, 587, 439, 459, 788, 719, 958,
       516, 748, 686, 451, 636, 375, 982, 557, 922, 479, 792, 957, 846,
       525, 289, 142, 162, 584, 591, 239, 847,  98, 786, 617, 630, 939,
       106, 143, 480, 443,  51,  74, 300, 823, 907, 559, 902,  25,  37,
        33, 160, 871, 698, 273, 851, 462, 157, 780, 597, 569,  21, 605,
       257, 446, 250, 245, 416,  88,  50, 692, 633, 110, 567, 583, 505,
        65, 769, 504, 427, 657, 722, 997, 266, 522, 862, 526,  15, 346,
       306, 795, 723, 714, 272, 354,   4, 971, 138, 895, 975, 428, 133,
       510, 411,  52, 423, 470, 511, 513, 356, 715, 656, 405, 313, 530,
       994, 783, 836, 816, 647, 403, 246, 171, 507, 151, 545, 284, 325,
       909, 927, 886, 818, 693, 483, 394, 931, 666, 612, 122, 252, 539,
       279, 433, 259, 317,  31, 977, 613, 262, 475, 461, 799,  22, 333,
        23, 341, 978, 670, 651, 132, 890, 365, 554, 214, 109, 637, 312,
       677, 447, 946, 896, 749, 320, 814, 442, 920, 860, 546, 360, 822,
       124, 930, 614,  67, 318, 650, 165, 118, 438, 244, 972, 521, 334,
       301, 497, 960, 850, 296, 324, 887, 558, 515, 286, 217, 350, 280,
       690, 884, 444, 434, 761, 643, 949, 663, 990, 172,  18, 669, 724,
       146, 833, 340, 837, 348, 500, 845, 933, 330, 913, 639, 278, 779,
       135, 219, 195, 695, 577, 261, 541, 468, 988, 295, 353, 414, 449,
       561, 687, 615, 532, 291, 764, 547, 366, 464, 950, 232, 477, 773,
       344,   9, 102, 241, 243, 789, 422, 852, 808, 166, 648, 548,  47,
       835, 952,  82, 984, 489, 813, 829, 998, 983, 201, 879, 178, 849,
       718, 864, 150, 638, 421, 713, 127,  16, 169, 553, 367, 750, 892,
       208, 149, 358, 290, 739, 465, 756, 821, 967, 173, 534, 345, 732,
        76,  66,  69, 921, 883, 370, 570, 668, 448, 441, 551, 362, 288,
       793, 401, 520, 331, 311, 206, 571, 226, 453, 954, 113, 784, 380,
       292, 941, 699, 867, 269, 126, 540, 625, 645, 174, 374, 275, 202,
       338, 891, 744, 730, 602, 121, 503,  92, 672, 412, 361, 826, 712,
       474, 564, 417, 866, 440, 832, 727, 237, 825, 652, 970, 563, 766,
       131, 327, 218, 940,   5, 705, 641, 678, 828, 620, 755, 562, 848,
       772, 256, 199, 787, 590, 653,  42, 961, 810, 654, 233, 735, 544,
       737, 302, 112, 924, 955, 992, 397, 667, 469, 911, 664, 287,  28,
       805, 161, 326, 496, 419, 248, 763, 870, 683, 993, 937, 716, 991,
       934, 372, 535,  41, 518, 336, 556, 378, 141,  62, 905,  27, 369,
       640, 632, 175, 721,   8, 629, 868,  79, 527, 574, 148, 147, 979,
       579, 609, 529, 691,  64, 757, 673, 238,  84, 115, 628, 758,  99,
       754, 635, 875, 392, 519, 343, 155, 973, 610, 114, 197, 194, 906,
       297, 499, 424, 136, 900, 347, 413, 339, 189, 777, 125, 684, 549,
       123, 820, 965, 910, 881,  81, 704,  53, 915,  44, 177, 778, 537,
       211, 163, 523, 478, 741, 607,  68, 903, 932, 328, 153, 603, 843,
       402, 655, 627, 436, 694, 229, 231, 894,  75, 258, 914, 455, 357,
       528, 298, 918,  48, 753, 267, 675, 368, 919, 103,  61, 517,  36,
         7, 936, 223, 731,  20, 445, 156, 660,   0,  32, 631, 310, 701,
       335, 711, 316, 781, 776, 387, 969, 385, 944, 893, 314, 234, 604,
       565, 494,  59, 680, 205, 853, 236, 634, 282, 188,  80, 466, 342,
        17, 167, 137, 460, 999, 752, 916, 595, 307, 452, 191, 170, 389,
       391, 410,  96, 834, 770, 322, 964, 968, 882, 158, 708,  97, 658,
        34, 588, 726, 935, 351, 586, 159, 533, 283, 265, 774, 274, 696,
       457, 408, 264, 842, 775, 384, 355, 976, 395, 622, 128, 260, 329,
       616, 376, 856,  13, 409, 396, 888, 815, 742, 432, 386,  91, 844,
       111, 762, 812, 304, 966, 398, 794, 101,  56, 809, 951, 463,  43,
       209, 207, 593, 981, 797, 582, 425, 426, 227,  83, 782, 679, 573,
       676, 948, 581, 962, 674, 200, 119, 555, 589, 621, 608, 186, 509,
       987,  14,  19, 611, 697,  29, 472, 293, 203, 220, 552, 945,  30,
       745, 281, 242, 995,  73, 482, 899, 437, 181, 363, 717, 649, 418,
       487, 538, 953, 176, 154, 268, 947, 840, 985, 702, 646, 117, 514,
       235,  95, 383, 740, 659, 880, 733, 986, 473,  49, 644, 352, 706,
       594, 493, 662, 876, 601,  38, 184,  39, 568, 454, 294, 804, 216,
        77, 536, 105, 807, 575, 498, 501, 224, 204, 319, 337, 249,  45,
       190, 736, 803, 315, 560, 471, 524, 467, 145, 959, 830, 430, 963,
       129, 303, 415, 817, 707, 221, 790, 491, 116, 196, 709, 222, 681,
       725, 193, 592, 618, 100, 917, 495, 406, 183, 542, 578, 488,  85,
       309,  93,   1, 456, 251, 929,  26, 277, 759, 928, 240, 212, 399,
       276, 700, 839, 926, 885, 765, 373, 420, 746, 626, 379, 858, 734,
       120,  54, 798, 806, 285, 332, 435, 179,  89, 572, 623, 566, 458,
       838, 827, 671, 861, 938, 192, 738, 600, 596, 388, 476, 943, 134,
       104, 878, 263,  90, 225, 767, 599, 901, 407, 308, 819, 270, 377,
        87, 107, 682, 168, 942, 728,  55, 485, 531, 164, 512, 811,  63,
       872,   6,  70, 642, 863, 228, 801, 747, 908, 247, 182, 897, 904,
       585, 299, 996, 543, 255, 720, 139, 390, 321, 349, 771, 429, 980,
        86,  94, 729, 492,  72, 768, 869,  46, 576, 400,  58, 925])

In [9]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,108
1,female,group C,some college,standard,completed,69,90,88,305
2,female,group B,master's degree,standard,none,90,95,93,152
3,male,group A,associate's degree,free/reduced,none,47,57,44,180
4,male,group C,some college,standard,none,76,78,75,393
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,46
996,male,group C,high school,free/reduced,none,62,55,55,576
997,female,group C,high school,free/reduced,completed,59,71,65,400
998,female,group D,some college,standard,completed,68,78,77,58
999,female,group D,some college,free/reduced,none,77,86,86,925

# 2 Set index

In [13]:
# set new_index column as index
# df_exams.set_index('new_index', inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
108,female,group B,bachelor's degree,standard,none,72,72,74
305,female,group C,some college,standard,completed,69,90,88
152,female,group B,master's degree,standard,none,90,95,93
180,male,group A,associate's degree,free/reduced,none,47,57,44
393,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
46,female,group E,master's degree,standard,completed,88,99,95
576,male,group C,high school,free/reduced,none,62,55,55
400,female,group C,high school,free/reduced,completed,59,71,65
58,female,group D,some college,standard,completed,68,78,77
925,female,group D,some college,free/reduced,none,77,86,86

# 3 Sort index

In [14]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,female,group B,bachelor's degree,standard,completed,66,74,81
1,female,group E,associate's degree,standard,completed,93,100,95
2,female,group E,master's degree,standard,none,62,68,68
3,male,group B,associate's degree,standard,none,65,54,57
4,female,group C,master's degree,standard,completed,81,91,87
...,...,...,...,...,...,...,...,...
995,female,group C,associate's degree,standard,completed,52,59,62
996,male,group C,associate's degree,standard,none,62,65,58
997,male,group B,master's degree,free/reduced,none,49,53,52
998,male,group D,some college,free/reduced,none,59,62,61
999,female,group B,bachelor's degree,free/reduced,none,77,85,87

In [16]:
# sort descending by index
df_exams.sort_index(ascending=False, inplace=True)

In [17]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group B,bachelor's degree,free/reduced,none,77,85,87
998,male,group D,some college,free/reduced,none,59,62,61
997,male,group B,master's degree,free/reduced,none,49,53,52
996,male,group C,associate's degree,standard,none,62,65,58
995,female,group C,associate's degree,standard,completed,52,59,62
...,...,...,...,...,...,...,...,...
4,female,group C,master's degree,standard,completed,81,91,87
3,male,group B,associate's degree,standard,none,65,54,57
2,female,group E,master's degree,standard,none,62,68,68
1,female,group E,associate's degree,standard,completed,93,100,95
0,female,group B,bachelor's degree,standard,completed,66,74,81