In [3]:
import pandas as pd

In [5]:
# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1 Selecting two or more columns

In [13]:
# select 2 columns using [[]]
df_gender_and_math_score = df_exams[["gender", "math score"]]

In [14]:
# check out the data type of the selection
type(df_gender_math_score)

pandas.core.frame.DataFrame

In [15]:
# select 2 or mo re columns using [[]]
df_exams[["gender", "math score", "reading score", 'writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [ ]:
# we can't select 2 or more columns with the '.'