In [1]:
import pandas as pd

# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1 Adding a new column

## 1.1 Adding a new column with a scalar value

In [2]:
# adding ne column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## 1.2 Adding a new column with an array
The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [4]:
import numpy as np

In [6]:
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [7]:
# length of the array 
len(language_score)

1000

In [9]:
# adding a new column to datafreame with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [21]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(0, 101, size=1000)

In [22]:
# min value inclusive and high value exlusive
min(int_language_score), max(int_language_score)

(np.int32(0), np.int32(100))

In [24]:
# adding a new column 
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,66
1,female,group C,some college,standard,completed,69,90,88,84
2,female,group B,master's degree,standard,none,90,95,93,20
3,male,group A,associate's degree,free/reduced,none,47,57,44,84
4,male,group C,some college,standard,none,76,78,75,11
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,16
996,male,group C,high school,free/reduced,none,62,55,55,63
997,female,group C,high school,free/reduced,completed,59,71,65,83
998,female,group D,some college,standard,completed,68,78,77,94
999,female,group D,some college,free/reduced,none,77,86,86,32

In [26]:
# create random float numbers between 1 and 100
np.random.uniform(0, 101, 1000)

array([ 69.07740876,  26.55461435,  49.7979326 ,  51.26371007,
         9.82375831,  36.65727932,  20.4065901 ,   0.51710097,
        74.19659905, 100.27644254,  39.73490071,  26.98403347,
        71.00697959,  93.1524285 ,  25.89035969,  21.72961013,
        30.92667075,  75.48577271,  97.9016818 ,  94.89922902,
         8.06572303,  87.26520529,  84.98343685,  47.7667819 ,
        41.33539565,  74.62400071,  77.89685137,  13.22502682,
        27.35891328,  16.72881101,  38.70047718,  17.44620945,
        10.90342655,  50.10324758,  99.61018434,  79.66893538,
        79.19616158,  65.75561792,  35.24931857,  67.01555357,
        38.13419701,  23.72306049,  59.88072695,  59.71387489,
        19.68073449,  25.58831222,  67.2557901 ,  23.91660496,
        80.78105741,   7.25003559,  97.47294526,  94.33122166,
        93.82502234,  60.56042275,  21.82078546,   5.89699275,
         6.24481642,   2.08693653, 100.59874382, 100.0163866 ,
        91.43822032,  24.60692924,  44.3590269 ,  18.25252211,
        94.04423691,  83.01285989,  62.10247229,  96.84541819,
        24.38528068,  77.47296128,  68.34135575,  20.83351464,
        88.99584487,  11.94413736,   1.24391726,  78.53166685,
        88.13985468,  82.63121822,   3.48237546,  32.66933857,
        87.49084819,  23.27981017,  43.92439934,  55.11797517,
        14.46200482,  83.63715294,  58.52597266,  79.5631267 ,
         4.65096875,  23.94668344,  59.99502266,  30.72187705,
        21.55386761,  62.66743414,  58.47097804,  34.82144155,
        23.23279159,  28.41747985,  73.9607456 ,  63.77193983,
        37.82304928,  49.46296364,  96.69771595,  10.52399819,
        63.53100177,   1.85458182,  12.29287567,  22.85896056,
        26.94175052,  61.64937877,   0.67151906,   4.51365668,
        94.69847714,  87.03427019,  22.88533642,  17.08456084,
         3.81793276,  34.58493454,  81.7751884 ,  74.00075844,
        49.55765874,  67.11754682,  32.93731912,  75.257468  ,
         4.58109864,   0.69252634,  54.6702217 ,  69.19734847,
        32.87156829,  32.91520703,  94.67234641,  60.74496423,
        22.30747899,  99.57670501,  77.94889839,  42.2434621 ,
         2.33014886,  34.12483912,  69.51954681,  26.57024854,
        37.61831351,  49.55637835,  78.46398421,  58.95178326,
        16.25397542,  55.32516382,  53.60189286,  72.59641626,
        19.82880861,  48.28620422,  81.84427015,  22.27032357,
        96.62957536,  30.93254497,  27.15741065,  91.20924034,
        26.33835038,  72.06156273,  62.77395815,  31.90829813,
        15.13399407,  92.97678094,  73.73313721,  20.15538469,
        63.89222873,  83.45308811,  55.48770755,  99.67494372,
        63.48983701,  81.60305688,  69.55764162,  51.37916277,
        39.97112756, 100.25255595,  57.20537816,  60.07897071,
         3.6041192 ,  60.99804548,  49.83137621,  68.08943943,
        33.73058728,  95.8238359 ,  87.98320793,  69.68630917,
        80.31345265,  47.06181721,  45.36819954,  67.15915877,
        80.78750177,  18.86018473,  39.35207099,  75.88493183,
        67.11337747,  17.02643605,   7.33671576,  18.66937241,
        76.11096255,   7.83372667,  77.95945614,  47.11597826,
        44.54781056,   8.22541942,  62.26829331,  84.52021025,
        84.04789586,  11.28388762,  57.84362631,  97.40005723,
        40.35044699,  53.00147848,  26.85225538,  41.14290218,
        51.07670076,  84.39713852,  71.98583387,  16.85395613,
        90.82538968,  66.12355053,  41.10850907,  80.7217829 ,
        76.4859585 ,  37.83558484,  69.58484656,  49.17338577,
        41.66532592,  60.37502818,  14.41851728,  79.41950274,
        19.09856763,  45.25892012,   9.82909301,  62.7187548 ,
        55.75658474,  71.1806096 ,  93.12391974,  27.27126494,
        60.18864007,  59.11421648,  49.19561767,  98.77585281,
         7.0947646 ,  40.01305254,  69.96350643,  22.30807072,
        79.10223898,   4.54629611,  64.68730902,  24.79080535,
        16.91897797,  85.87200376,  50.1759851 ,  19.66684985,
        13.27775627,  36.8716528 ,  86.53768346,   1.22603058,
        21.03166617,  58.32580896,  49.81001286,  82.89230036,
        48.71433166,  63.97863923,  31.19643316,  89.99165429,
         4.57750294,  43.49387122,  30.50740658,  89.12996267,
        11.69356464,  76.00270404,  90.05976581,  86.76885338,
         6.61166171,  63.08484689,  73.81591707,  46.14722086,
        96.36746258,  80.29979619,  32.18008783,   1.07796369,
        74.22161811,  61.83754084,  11.31988077,  53.36576677,
        64.57445215,  92.65156195,  18.13198084,  25.98548971,
         6.27867236,  77.80468399,   2.41728162,  81.11010112,
        84.54161117,   1.30942314,  95.24510543,   5.48859123,
        61.52607133,  39.69152826,   3.32877121,  58.1217207 ,
        47.40369902,  45.55833073,  83.74160422,  91.93033466,
        28.06573275,   9.46128837, 100.40064598,  53.28074438,
        56.00104382,  47.59407045,  79.97232822,  52.44179856,
        25.03606537,  62.22433954,  83.0239411 ,  12.78969099,
        80.62298992,  84.05644509,   9.95534561,  30.64864222,
        51.40927393,  54.17590375,  87.23479297,  31.309082  ,
        11.64263524,  68.58548435,  80.96177949,  19.53281515,
        41.73779658,  59.3152216 ,  92.74612752,  21.57320526,
        48.96090689,  71.08438183,   4.32942679,  75.10551342,
        95.00246527,  25.80952181,  99.04130997,  69.11774489,
        93.08138617,  21.14613207,   3.01315026,   3.17139734,
        19.59311214,  44.36434202,  47.06823113,  93.7427625 ,
        43.98504858,  32.14891844,   0.90212821,  46.90374623,
        43.19707822,  26.36347795,  63.48626794,  74.08299561,
        61.94842762,  12.19509537,  87.17744942,  71.75437212,
        20.66658503,  16.60385134,  85.42974775,  39.67031578,
         4.71048145,  77.82334585,  84.48414217,  88.50932681,
        85.80467454,  50.10037518,  58.98430334,   2.70750091,
        43.43108809,  47.56155617,  39.35548878,  20.19490447,
         0.37483013,  60.08197465,  65.97215713,   2.75569764,
        53.31751163,  92.07480104,  26.75446334,  70.6335507 ,
        21.72964164, 100.7971239 ,  32.31886141,  73.90981156,
        50.65049309,  45.09657241,  92.58313435,  43.5560802 ,
        78.14157985,  36.0345667 ,  52.14881134,  87.86980552,
        23.11724262,  10.13694254,   8.18996125,  20.36074663,
         2.87638735,   2.33696409,   2.74553249,  36.50036927,
        43.91452525,   5.94675142,  83.35690212,  56.0169125 ,
        76.04727464,  58.93079406,   8.65096189,  85.33041978,
        65.88417136,  59.21136825,  52.0619369 ,  33.90062219,
        35.50466832,  29.54011692,   1.1284195 ,  42.75381457,
        49.0581012 ,  69.27446667,   5.26340712,  19.56693478,
        89.32712753,  24.33161357,  58.25848333,  27.6404123 ,
        70.48403579,   6.71262332,  28.72952737,  30.41469321,
        39.53583025,  12.7378912 ,  69.7004045 ,  97.58742421,
         4.43352678,  53.40669417,  89.011021  ,  34.83470866,
        79.18407726,  95.05964463,  43.27044163,  37.674322  ,
        18.28226549, 100.40181752,  42.35543897,  29.1881682 ,
        58.88166823,  87.80883203,   4.86531329,  15.53540669,
        70.19037885,  97.17314214,  61.02097785,  89.69519913,
         8.05024423,  90.76817761,  20.1263446 ,  23.72724591,
         0.34950089,  52.52472835,   6.81066128,  96.43577439,
        29.401714  ,  74.68634216,   2.13955715,   0.43650381,
        87.41424865,   9.77162377,  63.82636865,  17.17309627,
        53.96113951,  66.93398245,  61.30881211,  51.59468154,
        10.69153595,  52.74628389,  30.58542296,  95.82072498,
        32.689689  ,  40.44070936,  45.52147287,  96.22871343,
        13.6769349 ,  22.09731675,  51.23926642,  11.88708595,
        51.11477918,  87.97726734,  11.94902285,  92.79983005,
        10.56261491,  55.59012208,  12.9718586 ,  91.94751505,
        34.725042  ,  60.66142774,  12.0853397 ,  47.04578637,
        98.68236252,  20.90483485,  31.67857783,  29.72870715,
        98.68773107,  99.97088317,  60.56164966,  63.29530622,
        42.69679735,   1.35588243,  20.04582903,   6.14630027,
        54.84339266,  65.34390043,   1.63004285,  88.72345902,
        32.70214412,  12.1345022 ,  89.47653789,  65.01124826,
        30.74252894,  54.42216663,  28.44408465,  58.22829328,
        15.24911994,  26.99870166,  11.39468138,  94.2529135 ,
        42.06123638,  89.49695469,  43.54398829,  89.52513321,
        66.69445129,   2.29721829,  89.23610384,  23.1288764 ,
        80.41338321,  19.75004427,  91.55330683,  16.10130432,
        76.19885481,  58.94159497,   1.89969815,  58.24191784,
        47.71227563,  25.69088059,  93.0815904 ,  29.12856743,
        64.67719383,  29.50483218,  85.08940001,  36.5832438 ,
        71.08660047,  77.2439003 ,  86.42572121,  86.32509941,
        42.07320706,  67.44173774,  52.48478939,   2.04172625,
        49.18025197,   9.38412762,  86.390008  ,  76.77876459,
        16.09845229,  20.7762006 ,  23.21651694,  95.34762077,
        54.18475403,  67.91971948,   6.41150299,  87.59709367,
        30.7084512 ,  22.18412004,  27.70021507,  25.47130471,
        68.57230114,  53.13845453,  23.35017643,  78.38251747,
        88.45821134,  31.98251749,  30.23020926,  99.57984803,
        74.28449366,  13.6539684 ,  31.33200507,  30.02197227,
        41.91611555,  29.08679019,  87.46613154,  80.04409672,
        83.25465745,  25.66635013,  85.41378553,  80.00658654,
        86.79621932,  21.37630173,  52.62779123,  47.80592272,
        56.32747533,  93.79969469,   8.87195974,  51.32612496,
        62.29035195,  85.18453902,  55.26631591,  32.30463127,
        74.38882429,  13.24777867,  69.41244386,   0.40894876,
        59.31432081,   5.75599376,  45.45221337,  92.57841451,
        56.32089631,  31.81918541,  58.10956609,  12.95211704,
        34.25389691,  55.57221484,  79.9470143 ,  40.4834503 ,
        56.09820777,  73.1926022 ,  55.40088176,  20.73392845,
        52.48266269,  56.36134998,  50.88239278,  75.25242822,
        91.73426704,  85.97476207,  76.20325585,  39.23931896,
        20.87565156,   4.27302585,  40.01599578,  26.13684032,
        45.74076822,   1.14334692,  67.27106993,  83.95870582,
        67.49780779, 100.48112115,  81.52351845,  47.55677602,
        12.89860978,  99.22107041,  74.78949343,  96.48687184,
         0.90882131,  74.3897968 ,  73.98714692,  50.67014503,
        72.0302754 ,  42.9681423 ,  41.27635874,  35.32704248,
        47.54355377,  11.2436612 ,  65.40393226,  46.68722908,
        66.24866234,  80.11083625,  36.16135217,  97.38116715,
        35.66220474,  40.94143879,  51.5742669 ,  37.88451017,
        17.19211796,  86.36189027,  91.21495019,  28.84457494,
        34.58031244,  26.46024938,  86.6898049 ,  88.49379186,
        27.3381316 ,  48.57028848,  75.45273832,  44.87285427,
        28.06195627,  82.5442066 ,  71.28552052,  70.11884594,
        56.36399359,  46.60563339,  95.94736454,  71.18159285,
         8.66160779,  55.23482669,  68.34501753,  79.61855392,
        35.51296985,  18.04548254,   8.50868017,  83.47194602,
        83.09406572,  11.64457283,   1.33369442,  78.95019852,
        56.50646355,  99.10357238,  89.63720337,  23.95866826,
        12.18019444,  18.33056437,   4.33252021,  20.68663427,
        98.50980524,   0.73475667,  48.98506977,  96.05691023,
        44.85113572,  82.73064385,  62.81292755,  42.60789575,
        69.51393745,  76.71700507,  22.23408007,  79.36550271,
        84.14287157,  98.76570715,   2.56381261,  40.30513151,
        87.74884434,  82.08389035,  68.61769491,  47.83829336,
        87.11715192,  72.39423853,  19.58452066,  23.34391723,
        69.53649501,  44.27811257,   7.93664499,  56.4828392 ,
        14.92425301,  81.01360274,  77.25479329,  97.53469389,
        79.83389987,  53.22562386,  72.90572814,  92.87809735,
        29.77869237,  11.7186716 ,  20.22789411,  40.71064001,
        60.46143936,  72.05295404,  23.04586209,   7.62466382,
        81.0624561 ,  60.50455238,  62.78161227,  50.12282569,
        48.6782398 ,  63.75518815,  63.76786478,  41.66360286,
        50.6832762 ,  33.41869882,  78.54305419,  31.84138144,
        25.94331596,  11.89538836,  52.2965397 ,  44.19972633,
        16.61841593,  67.91664212,  43.94141653,  45.16629402,
         8.35958131,  75.77332584,  33.3826083 ,  64.80422603,
        44.26148607,  11.09662618,  14.97844011,  45.04520575,
        59.11481508,  30.53609308,  65.77330371,  83.90377191,
        89.0309866 ,  20.32221518,  50.95749178,  51.65595655,
        25.4555915 ,  78.35196551,  32.74947501,   5.42765254,
        26.68151358,   4.37150863,  95.60305086,   0.4645393 ,
        63.6696847 ,  15.87497546,  53.65919436,  11.15412408,
        66.86858192,  69.97092539,  26.26616526,   7.91573535,
         0.16890181,   7.23152694,  53.78107126,  40.08085517,
        71.81961691,   4.28659963,  40.15794991,  49.62938644,
        82.48748056,   4.07289313,  23.70251284,  28.357238  ,
        48.55491546,  44.11524222,  56.30836931,  91.93617828,
        83.46577861,  81.41310454,  18.84863284,  79.91279699,
        77.1865019 ,  23.83965182,  74.35236587,  36.1894093 ,
        59.04565554,  36.59273247,  42.43061145,  58.23232895,
        14.05228782,  27.27570937,  16.83813227,  84.63645972,
        48.98097889,  45.27313077, 100.85274401,  15.5131918 ,
         6.95913739,  73.15260291,  17.85001387,  67.78987359,
        43.54157794,  15.25741849,  18.51255956,  96.50630752,
        97.64925213,  56.44053308,  57.06026925,  38.07978668,
        61.8639752 ,  54.78641021,  29.12616077,  41.98093299,
        44.09355085,  84.27117447,  51.693799  ,  21.85985337,
        96.55732162,  16.18925076,  93.54416722,  30.25831697,
        47.2663818 ,  21.31866823,  92.42508695,  35.72282765,
        39.93973944,  13.28432728,  11.02443479,  17.64012143,
        58.98704631,  22.00792252,  25.14677926,  13.74282355,
        84.42024397,  55.72157526,  83.84011438,  47.42286437,
        19.05144584,  90.46850938,   9.38733395,  40.63076654,
        52.52073929,  23.81574114,  73.91692445,  58.50496587,
        66.4430362 ,  10.4485497 ,  31.22666553,   0.98232485,
        67.78801112,  43.38866938,  72.38708178,  81.53550205,
        87.94014642,  71.04837409,  69.17525681,  77.41489664,
        52.56489963,  54.82189624,  39.4273631 , 100.56655322,
        64.65265875,  36.21742209,  17.61057394,  34.47877522,
        59.16011794,  34.69128134,  35.675757  ,  48.12068759,
         2.47347363,  80.92531947,  78.14135506,  54.95753981,
        17.68344437,  67.49601642,  35.72535152,  92.79424434,
        55.99038822,  81.4341393 ,  98.61420085,  87.60537153,
        54.0734518 ,  39.09971286,  19.48868184,   1.05995714,
        87.14975861,  94.71515029,  74.14883646,  43.12176505,
        48.21497332,  20.42364284,  30.63068235,  94.42404667,
        67.67332276,  48.38731004,  23.00254823,  31.90789722,
        85.91156785,  71.07512629,  38.47743263,  39.25244303,
        18.63095733,  93.43843911,  58.84854245,  85.82466456,
        48.16730101,   0.20692323,   1.71811563,  44.73962317,
        67.924933  ,  88.13393084,  83.36356446,  42.79737934,
        52.89456195,  37.84496936,  81.34994956,  72.90863126,
        37.42773219,  37.78419185, 100.17649261,   2.82060952,
        24.47929557,  13.1417919 ,  79.32702585,  48.63901702,
        10.54602186,  47.1426571 ,  37.99265989,  97.78397616,
        47.96984103,   6.89120247,  28.33722271,  36.18620938,
        69.70767088,  92.48147115,   8.64879064,  43.16465405,
        98.1139993 ,  22.10016997,  44.39084212,  27.10581557,
        84.32555874,  93.04194505,   4.51064983,  33.9209938 ,
        90.3633132 ,  81.48385682,  25.49360901,  78.25318112,
        95.18703195,  27.54883029,  93.50762242,  75.44413524])