In [1]:
import pandas as pd

# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 1 Adding a new column

## 1.1 assign()

When to use assign?
- add multiple columns in a single line of code
- when you need to overwrite the values of an existing columns (best practice)

If returns a new object (a copy) with all the original columns in addition to the new ones

In [2]:
import numpy as np

In [5]:
# create random numbers for our new score columns
score1 = np.random.randint(0, 101, size=1000)
score2 = np.random.randint(0, 101, size=1000)

In [9]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [11]:
# using assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)

In [12]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,85,90
1,female,group C,some college,standard,completed,69,90,88,49,99
2,female,group B,master's degree,standard,none,90,95,93,60,9
3,male,group A,associate's degree,free/reduced,none,47,57,44,12,56
4,male,group C,some college,standard,none,76,78,75,29,14
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,13,71
996,male,group C,high school,free/reduced,none,62,55,55,43,87
997,female,group C,high school,free/reduced,completed,59,71,65,9,34
998,female,group D,some college,standard,completed,68,78,77,77,55
999,female,group D,some college,free/reduced,none,77,86,86,57,12

## 1.2 insert()

Inserts a new column at a specific position of index

In [13]:
# using index to add a column at a specific pos
df_exams.insert(1, 'test', series1)

In [16]:
# show dataframe
df_exams.insert(10, 'test2', series2)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,test2,score2
0,female,85,group B,bachelor's degree,standard,none,72,72,74,85,90,90
1,female,49,group C,some college,standard,completed,69,90,88,49,99,99
2,female,60,group B,master's degree,standard,none,90,95,93,60,9,9
3,male,12,group A,associate's degree,free/reduced,none,47,57,44,12,56,56
4,male,29,group C,some college,standard,none,76,78,75,29,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,13,group E,master's degree,standard,completed,88,99,95,13,71,71
996,male,43,group C,high school,free/reduced,none,62,55,55,43,87,87
997,female,9,group C,high school,free/reduced,completed,59,71,65,9,34,34
998,female,77,group D,some college,standard,completed,68,78,77,77,55,55
999,female,57,group D,some college,free/reduced,none,77,86,86,57,12,12