In [5]:
import pandas as pd

# pivot()

In [7]:
# read and show the dataset
df_gdp = pd.read_csv('gdp.csv', encoding='windows-1251')
df_gdp

      unid wbid      country  year        SES       gdppc  yrseduc  popshare
0        4  AFG  Afghanistan  1970   3.474212   709.00000      NaN  0.003097
1        4  AFG  Afghanistan  1920  26.968016   731.75677      NaN  0.003245
2        4  AFG  Afghanistan  1990   1.269530   604.00000      NaN  0.002347
3        4  AFG  Afghanistan  1960  15.763076   739.00000      NaN  0.003039
4        4  AFG  Afghanistan  2000   2.061114   565.00000      NaN  0.003309
...    ...  ...          ...   ...        ...         ...      ...       ...
2081   716  ZWE     Zimbabwe  1940  52.746567   813.00000      NaN  0.001113
2082   716  ZWE     Zimbabwe  2010  27.091389  1388.97300      NaN  0.002074
2083   716  ZWE     Zimbabwe  1990  59.110970  2526.07230      NaN  0.002039
2084   716  ZWE     Zimbabwe  1900  54.722645   601.00000      NaN  0.000996
2085   716  ZWE     Zimbabwe  1960  53.811077   938.00000      NaN  0.001268

[2086 rows x 8 columns]

In [28]:
# reshape the dataframe with .pivot() 
df_gdp_pivot = df_gdp.pivot(index="country", columns="year", values="gdppc")
# df_gdp_pivot.loc['Russia']
df_gdp_pivot.head(50)

year,1880,1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010
country,,,,,,,,,,,,,,
Afghanistan,585.46509,635.93024,686.39532,736.86047,731.75677,702.83783,673.91895,645.000,739.000,709.0000,690.0000,604.00000,565.00000,1662.80350
Albania,522.00000,598.00000,685.00000,780.00000,861.31250,929.57141,965.28571,1001.000,1451.000,2004.0000,2347.0000,4557.40820,5470.01760,9927.17580
Algeria,819.18604,923.37207,1027.55810,1131.74410,1201.21620,1255.81080,1310.40540,1365.000,2088.000,2249.0000,3152.0000,10238.88400,10211.10400,12898.29600
Angola,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,1052.000,1253.000,1768.0000,961.0000,4806.43020,3831.00000,6492.17680
Argentina,1731.50000,2152.00000,2756.00000,3822.00000,3473.00000,4080.00000,4161.00000,4987.000,5559.000,7302.0000,8206.0000,10833.50300,14924.37400,18794.27000
Armenia,1041.00000,1139.00000,1237.00000,1430.07690,1432.93330,1448.00000,2144.00000,2841.000,3945.000,5575.0000,6116.5884,3735.54320,2918.55760,6507.91460
Australia,4285.00000,4458.00000,4013.00000,5210.00000,4766.00000,4708.00000,6166.00000,7412.000,8791.000,12024.0000,14412.0000,28572.07600,35244.50400,41363.21500
Austria,2079.00000,2443.00000,2882.00000,3290.00000,2412.00000,3586.00000,3959.00000,3706.000,6519.000,9747.0000,13759.0000,31265.28700,38812.05100,43174.97700
Bahrain,811.76746,881.53491,951.30231,1021.06980,1242.91890,1529.94590,1816.97300,2104.000,2843.000,3788.0000,4388.0000,35112.55500,44791.52000,39912.69500
Bangladesh,566.66669,587.33331,608.00000,661.84613,651.89191,614.59460,577.29730,540.000,545.000,630.0000,549.0000,1290.43100,1645.71730,2451.30520
Barbados,647.66669,746.33331,845.00000,1098.07690,1431.10820,1798.40540,2165.70260,2533.000,3478.000,4948.0000,5935.0000,13298.48500,14440.40900,15345.84300
Belgium,3065.00000,3428.00000,3731.00000,4064.00000,3962.00000,4979.00000,4562.00000,5462.000,6952.000,10611.0000,14467.0000,30701.26000,37253.47300,41086.55100
Belize,647.66669,746.33331,845.00000,1098.07690,1431.10820,1798.40540,2165.70260,2533.000,3478.000,4948.0000,5935.0000,5168.28860,6964.02390,7886.99760
Benin,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,1084.000,978.000,1027.0000,1128.0000,1456.01660,1646.46450,1759.38700
Bolivia,583.33331,680.66669,778.00000,978.00000,1180.62500,1384.37500,1588.12500,1919.000,1606.000,2176.0000,2572.0000,3707.30440,4412.32760,5407.60990
Botswana,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,349.000,403.000,647.0000,1765.0000,8099.26070,10361.31100,13119.55100
Brazil,752.00000,794.00000,678.00000,769.00000,963.00000,1048.00000,1250.00000,1672.000,2335.000,3057.0000,5195.0000,10245.83100,11308.43800,14405.93100
Brunei Darussalam,585.46509,635.93024,686.39532,736.86047,871.75677,1042.83790,1213.91890,1385.000,1632.000,2082.0000,2522.0000,85280.72700,82716.54700,79602.53900
Bulgaria,985.50000,1131.00000,1223.00000,1456.00000,1136.27270,1284.00000,1548.00000,1651.000,2912.000,4773.0000,6044.0000,9296.92970,8958.08890,15283.24600
Burkina Faso,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,474.000,609.000,745.0000,731.0000,844.34253,1075.39550,1420.93260
Burundi,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,360.000,444.000,540.0000,603.0000,1049.18140,713.26978,707.78760
Cambodia,585.46509,635.93024,686.39532,736.86047,700.91895,627.94592,554.97296,482.000,671.000,647.0000,828.0000,881.00000,1370.83070,2513.29320
Cameroon,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,671.000,832.000,982.0000,1192.0000,2768.32250,2403.86380,2574.97000
Canada,1816.00000,2378.00000,2911.00000,4066.00000,3861.00000,4811.00000,5368.00000,7291.000,8753.000,12050.0000,16176.0000,31299.65400,37431.91800,40699.35500
Central African Republic,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,772.000,925.000,891.0000,737.0000,932.87671,825.73743,888.71686
Chile,1740.00000,1966.00000,2194.00000,3000.00000,2768.00000,2859.00000,3236.00000,3670.000,4270.000,5231.0000,5680.0000,9244.15920,14887.89800,19357.47300
China,535.00000,540.00000,545.00000,550.38464,556.37500,568.00000,543.00000,448.000,662.000,778.0000,1061.0000,1526.40880,3700.74390,9525.81930
Colombia,819.00000,896.00000,973.00000,1162.00000,1255.00000,1474.00000,1895.00000,2153.000,2497.000,3094.0000,4257.0000,7533.51900,8308.22270,10900.50400
Congo,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,1198.000,1416.000,1696.0000,2324.0000,5256.71090,4647.95310,5595.29640
"Congo, Dem Rep",533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,570.000,748.000,768.0000,598.0000,1267.70640,518.49756,596.32288
Costa Rica,583.33331,680.66669,778.00000,978.00000,1624.00000,1626.00000,1763.00000,1963.000,2715.000,3754.0000,4911.0000,7787.16410,9878.27150,13000.01300
Croatia,1095.50000,1254.00000,1438.00000,1636.00000,1803.06250,1944.45460,1969.00000,2111.000,3070.000,4315.0000,5786.0000,7351.00000,15745.27800,20118.15600
Cuba,583.33331,680.66669,778.00000,978.00000,1300.93750,1505.00000,1208.00000,2046.000,2052.000,1917.0000,2644.0000,13694.41200,11289.78200,18433.90200
Cyprus,1815.00000,2028.00000,2361.00000,2721.76930,2536.00000,3291.00000,3824.00000,3846.000,4988.000,7399.0000,10436.0000,23300.77500,30085.90400,33941.28500
Czech Republic,1689.30250,1910.42800,2174.53200,2527.99560,2391.14920,2435.13450,2596.04590,2629.231,4102.689,6449.6768,8468.6406,19965.24600,21137.18200,28289.88900
Cфte d'Ivoire,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,1041.000,1256.000,1808.0000,2041.0000,3220.49460,2977.69530,2726.28860
Denmark,2181.00000,2523.00000,3017.00000,3705.00000,3992.00000,5341.00000,5116.00000,6943.000,8812.000,12686.0000,15227.0000,33843.96100,42430.00000,43757.73800
Dominican Republic,583.33331,680.66669,778.00000,978.00000,1035.91890,1032.94590,1029.97300,1027.000,1302.000,1561.0000,2372.0000,5267.10300,7963.70460,11123.53300
Ecuador,583.33331,680.66669,778.00000,978.00000,1108.80770,1209.96150,1356.00000,1863.000,2289.000,2845.0000,4129.0000,7472.02930,7387.61570,9352.34280
Egypt,707.83722,766.67444,825.51166,884.34882,903.51349,905.67566,907.83783,910.000,991.000,1254.0000,2069.0000,6014.30130,7556.71000,10102.10100
El Salvador,583.33331,680.66669,778.00000,978.00000,932.00000,1045.00000,1111.00000,1489.000,1764.000,2187.0000,2354.0000,4532.28660,6424.88720,7452.56150
Estonia,1041.00000,1139.00000,1237.00000,1430.07690,1432.93330,1448.00000,2144.00000,2841.000,3945.000,5575.0000,9547.6475,10820.00000,15703.02900,22740.96500
Ethiopia,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,390.000,440.000,595.0000,648.0000,652.35223,619.11432,1075.55370
Fiji,585.46509,635.93024,686.39532,736.86047,871.75677,1042.83790,1213.91890,1385.000,1632.000,2082.0000,2522.0000,5891.30620,6673.84720,7352.07130
Finland,1155.00000,1381.00000,1668.00000,1906.00000,1846.00000,2666.00000,3220.00000,4253.000,6230.000,9577.0000,12949.0000,28905.57000,34887.18000,39848.13300
France,2120.00000,2376.00000,2876.00000,2965.00000,3227.00000,4532.00000,4042.00000,5186.000,7398.000,11410.0000,14766.0000,29527.97500,34896.38700,36872.22700
Gabon,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,3108.000,4184.000,5869.0000,6777.0000,19499.55300,17776.35700,16334.47900
Gambia,533.66669,567.33331,601.00000,628.69232,682.62964,747.81482,813.00000,607.000,722.000,879.0000,1039.0000,1516.95940,1564.23340,1654.90810
Germany,1991.00000,2428.00000,2985.00000,3348.00000,2796.00000,3973.00000,5403.00000,3881.000,7705.000,10839.0000,14114.0000,31287.07000,36764.56300,40428.72300
Ghana,518.53491,598.06976,677.60468,757.13953,845.51349,937.67566,1029.83790,1122.000,1378.000,1424.0000,1157.0000,1919.59670,2272.71000,3083.86740

# pivot_table()

In [40]:
# read and show the dataset
df_sales = pd.read_excel("supermarket_sales.xlsx")
df_sales

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,13:28:00,Cash,618.38,4.761905,30.9190,6.6

In [43]:
# make a pivot table and add an aggregate function

# select_dtypes(include='number') автоматически выберет все инты и флоаты
numeric_cols = df_sales.select_dtypes(include='number').columns

# Строим pivot_table только по нужным столбцам
df_sales[[*numeric_cols, 'Gender']].pivot_table(index='Gender', aggfunc='sum')

,Quantity,Rating,Tax 5%,Total,Unit price,cogs,gross income,gross margin percentage
Gender,,,,,,,,
Female,2869,3489.2,7994.425,167882.925,27687.24,159888.50,7994.425,2385.714286
Male,2641,3483.5,7384.944,155083.824,27984.89,147698.88,7384.944,2376.190476

In [44]:
# make a pivot table, add an aggregate function and select some columns 
df_sales.pivot_table(index='Gender', 
                     values=['Quantity', 'Total'],
                     aggfunc='sum')

        Quantity       Total
Gender
Female      2869  167882.925
Male        2641  155083.824

In [45]:
# make a pivot tables that says how much male and female spend in each category
df_sales.pivot_table(index='Gender',
                     columns="Product line",
                     values='Total',
                     aggfunc='sum')

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,27102.0225,30437.400,33170.9175,18560.9865,30036.8775,28574.7210
Male,27235.5090,23868.495,22973.9265,30632.7525,23825.0355,26548.1055